[tool.poetry]
name = "GrimoireELK"
version = "0.77.0"
description = "GrimoireELK processes and stores software development data to ElasticSearch"
readme = "README.md"
authors = [
   "Bitergia <grimoirelab-discussions@lists.linuxfoundation.org>"
]
repository = "https://github.com/chaoss/grimoirelab-elk"
keywords = ["development repositories analytics"]
license = "GPL-3.0-or-later"
classifiers=[
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Topic :: Software Development',
    'License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)',
    'Programming Language :: Python :: 3',
    'Programming Language :: Python :: 3.6'
]

packages = [
   { include = "grimoire_elk"},
   { include = "tests", format = "sdist" },
]

include = [
  "grimoire_elk/enriched/mappings/*.json"
]

[tool.poetry.extras]
mysql = ["PyMySQL"]

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/chaoss/grimoirelab-elk/issues"

[tool.poetry.scripts]
p2o = 'utils.p2o:main'
gelk_mapping = 'utils.gelk_mapping:main'

[tool.poetry.dependencies]
python = "^3.6.1"
elasticsearch = "6.3.1"
elasticsearch-dsl = "6.3.1"
requests = "2.26.0"
urllib3 = "1.26.5"
geopy = "^2.0.0"
PyMySQL = "0.9.3"
pandas = "^1.0.5"
statsmodels = "^0.9.0"
sortinghat = {branch = "muggle", git = "https://github.com/chaoss/grimoirelab-sortinghat", optional = true}
grimoirelab-toolkit = {branch = "master", git = "https://github.com/chaoss/grimoirelab-toolkit"}
cereslib = {branch = "master", git = "https://github.com/chaoss/grimoirelab-cereslib"}
graal = {branch = "master", git = "https://github.com/chaoss/grimoirelab-graal"}
perceval = {branch = "master", git = "https://github.com/chaoss/grimoirelab-perceval"}
perceval-mozilla = {branch = "master", git = "https://github.com/chaoss/grimoirelab-perceval-mozilla"}
perceval-opnfv = {branch = "master", git = "https://github.com/chaoss/grimoirelab-perceval-opnfv"}
perceval-puppet = {branch = "master", git = "https://github.com/chaoss/grimoirelab-perceval-puppet"}
perceval-finos = {branch = "master", git = "https://github.com/Bitergia/grimoirelab-perceval-finos"}
perceval-weblate = {branch = "master", git = "https://github.com/chaoss/grimoirelab-perceval-weblate"}

[tool.poetry.dev-dependencies]
httpretty = "^0.9.6"
flake8 = "^3.9.2"
coverage = "^5.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
