name: build

on:
  push:
    branches:
      - sortinghat_graphql
  pull_request:
    branches:
      - sortinghat_graphql

jobs:
  tests:
    runs-on: ubuntu-latest
    services:
      # How to use MySQL
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

      # Redis
      redis:
        image: redis
        ports:
          - 6379:6379
        options: --health-cmd="redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
    
    name: Python ${{ matrix.python-version }} for ES ${{ matrix.elasticsearch-version }}
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        elasticsearch-version: [6.1.0, 7.2.0]
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install and set up Poetry
      run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

    - name: Runs Elasticsearch ${{ matrix.elasticsearch-version }}
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: ${{ matrix.elasticsearch-version }}

    - name: Install dependencies
      run: |
        source $HOME/.poetry/env
        poetry install -vvv

    - name: Verify Elasticsearch connection
      run: |
        curl -fsSL "http://localhost:9200/_cat/health?h=status"

    - name: Set MySQL mode
      env:
        DB_HOST: 127.0.0.1
        DB_PORT: ${{ job.services.mysql.ports[3306] }}
      run: |
        mysql --host $DB_HOST --port $DB_PORT -uroot -e "SET GLOBAL sql_mode = 'NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'";
        mysql --host $DB_HOST --port $DB_PORT -uroot -e "CREATE DATABASE sortinghat_db"

    - name: Run Sortinghat Server
      run: |
        source $HOME/.poetry/env
        git clone -b muggle --single-branch https://github.com/chaoss/grimoirelab-sortinghat /tmp/sortinghat
        cp tests/sortinghat_settings.py /tmp/sortinghat/config/settings/sortinghat_settings.py
        cd /tmp/sortinghat
        poetry install -vvv
        poetry run python manage.py migrate --settings=config.settings.sortinghat_settings
        poetry run python manage.py createsuperuser --username root --noinput --email 'root@root.com' --settings=config.settings.sortinghat_settings
        poetry run python manage.py runserver --settings=config.settings.sortinghat_settings &
        poetry run python manage.py rqworker --settings=config.settings.sortinghat_settings &
        cd

    - name: Lint with flake8
      run: |
        source $HOME/.poetry/env
        poetry run flake8

    - name: Tests and Coverage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        source $HOME/.poetry/env
        cd tests
        poetry run coverage run --source=grimoire_elk run_tests.py
        poetry run coveralls --service=github
